const assert = require('assert')
const fs = require('fs')

const listener = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavNotificationListener.java', 'utf8')
const activity = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/MainActivity.java', 'utf8')
const service = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavigationService.java', 'utf8')
const repository = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavStateRepository.java', 'utf8')
const manifest = fs.readFileSync('android/app/src/main/AndroidManifest.xml', 'utf8')
const androidBuild = fs.readFileSync('android/app/build.gradle', 'utf8')
const runtimePath = 'android/app/src/main/java/com/ringmap/nav/NavBridgeRuntime.java'
const recoveryPath = 'android/app/src/main/java/com/ringmap/nav/NotificationListenerRecovery.java'
const startupPath = 'android/app/src/main/java/com/ringmap/nav/StartupReceiver.java'

assert(listener.includes('requestRebind'), 'notification listener must request rebind after disconnect')
assert(listener.includes('ACTIVE_SCAN_INTERVAL_MS') && listener.includes('ACTIVE_SCAN_TASK'), 'connected listener must periodically rescan active navigation notifications')
assert(listener.includes('instanceId = LastNavCache.listenerConnected') && listener.includes('listenerDisconnected(instanceId'), 'stale listener lifecycle callbacks must not overwrite a newer connected instance')
assert(listener.includes('verifyNavigationEnded'), 'notification removal must verify that no active map navigation notification remains')
assert(!listener.includes('sbn.getKey().equals(activeKey)'), 'notification end detection must verify the whole source after OEM notification-key replacement')
assert(listener.includes('postDelayed'), 'notification end verification must tolerate notification replacement races')
assert(listener.includes('Handler'), 'notification listener needs an independent retry handler')
assert(listener.includes('Arrays.sort(active') && listener.includes('getPostTime()'), 'listener reconnect scans must process notifications in event-time order')
assert(fs.existsSync(runtimePath), 'the notification listener needs a bridge owner independent of the foreground service')
const runtime = fs.readFileSync(runtimePath, 'utf8')
assert(runtime.includes('RESTART_TASK') && runtime.includes('scheduleRestartLocked') && runtime.includes('postDelayed'), 'fatal bridge errors must recover through runtime-owned bounded backoff')
assert(runtime.indexOf('instance = runtime') < runtime.indexOf('server.start()'), 'runtime generation must be published before asynchronous WebSocket bind errors can arrive')
assert(runtime.includes('onServerStarted') && runtime.includes('current.started = true'), 'bridge readiness must be confirmed only by WebSocket onStart')
assert(listener.includes('NavBridgeRuntime.ensureStarted'), 'notification callbacks must bootstrap the local bridge without opening the phone UI')
assert(fs.existsSync(recoveryPath) && fs.existsSync(startupPath), 'OEM listener recovery needs centralized rebind logic and boot/update recovery')
const recovery = fs.readFileSync(recoveryPath, 'utf8')
assert(recovery.includes('REBIND_COOLDOWN_MS') && recovery.includes('NotificationListenerService.requestRebind'), 'OEM recovery must use cooldown-protected platform rebind requests')
assert(!recovery.includes('setComponentEnabledSetting'), 'listener recovery must never toggle the component because OEMs can revoke access')
assert(manifest.includes('BOOT_COMPLETED') && manifest.includes('MY_PACKAGE_REPLACED'), 'listener recovery must run after boot and app update')
assert(!service.includes('NavDataBus.setListener(this)'), 'foreground service must not be the sole in-process navigation bridge owner')
assert(service.includes('NavBridgeRuntime.ensureStarted'), 'foreground service must attach to the shared bridge runtime when available')
assert(activity.includes('NotificationAccess.isGranted'), 'activity must use the centralized official notification access API')
assert(service.includes('NotificationAccess.isGranted'), 'service must use the centralized official notification access API')
assert(manifest.includes('POST_NOTIFICATIONS'), 'Android 13+ foreground-service status needs the notification permission declaration')
assert(activity.includes('requestNotificationsPermissionIfNeeded'), 'foreground-service notification permission must be requested from a foreground activity')
assert(androidBuild.includes('buildConfig true'), 'diagnostic version labels require AGP BuildConfig generation')
assert(!activity.includes('rebindAttempts < 6'), 'activity must not force re-authorization after a fixed retry count')
assert(activity.includes('AutoStartManagementActivity') && activity.includes('StartupAppListActivity'), 'stuck listeners need direct HyperOS and ColorOS autostart settings routes')
assert(service.indexOf('startForeground(NOTIFICATION_ID') < service.indexOf('ensureBridge();'), 'foreground service must enter foreground before attaching to the local bridge')
assert(manifest.includes('FOREGROUND_SERVICE_SPECIAL_USE'), 'long-running bridge service needs the specialUse foreground-service permission')
assert(manifest.includes('android:foregroundServiceType="specialUse"'), 'long-running bridge must not use Android 15 time-limited dataSync foreground service')
assert(manifest.includes('android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE'), 'specialUse foreground service must declare its reviewable subtype')
assert(!manifest.includes('FOREGROUND_SERVICE_DATA_SYNC'), 'time-limited dataSync permission must be removed')
assert(!service.includes('onTimeout(int startId, int fgsType)'), 'specialUse service must not carry obsolete dataSync timeout handling')
assert(repository.includes('clearWatchAckLocked();'), 'ending a navigation session must clear its watch ACK timing')
assert(repository.includes('if (previousSeq != snapshot.optLong')
  && repository.includes('clearWatchAckLocked();'),
  'a new navigation sequence must not inherit a previous watch ACK timestamp')
assert(!service.includes('client(s): " + json'), 'navigation JSON with route text must never be written to Logcat')
const socketServer = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavWebSocketServer.java', 'utf8')
assert(socketServer.includes('LastNavCache.authorityState()'), 'reconnect must atomically choose a fresh snapshot or a newer idle response')
assert(socketServer.includes('NavBridgeRuntime.onFatalServerError'), 'fatal WebSocket failures must release the runtime for automatic restart')
assert(socketServer.includes('connection.isOpen()') && socketServer.includes('clients.remove(connection)'), 'closed localhost clients must be pruned from the bridge client set')
assert(socketServer.includes('setReuseAddr(true)'), 'bridge restarts must retain localhost address reuse for rapid port rebinding')
assert(socketServer.includes('setConnectionLostTimeout(0)'), 'server heartbeat must be disabled because ZeppOS can intentionally suspend App-Side while asleep')
assert(!socketServer.includes('"superseded"') && !socketServer.includes('existing.close'), 'parallel Zepp App-Side contexts must not evict each other and create a reconnect loop')
console.log('android lifecycle tests passed')
