const assert = require('assert')
const fs = require('fs')

const listener = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavNotificationListener.java', 'utf8')
const activity = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/MainActivity.java', 'utf8')
const service = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavigationService.java', 'utf8')
const repository = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavStateRepository.java', 'utf8')
const manifest = fs.readFileSync('android/app/src/main/AndroidManifest.xml', 'utf8')
const androidBuild = fs.readFileSync('android/app/build.gradle', 'utf8')
const runtimePath = 'android/app/src/main/java/com/ringmap/nav/NavBridgeRuntime.java'

assert(listener.includes('requestRebind'), 'notification listener must request rebind after disconnect')
assert(listener.includes('verifyNavigationEnded'), 'notification removal must verify that no active map navigation notification remains')
assert(listener.includes('postDelayed'), 'notification end verification must tolerate notification replacement races')
assert(listener.includes('Handler'), 'notification listener needs an independent retry handler')
assert(listener.includes('Arrays.sort(active') && listener.includes('getPostTime()'), 'listener reconnect scans must process notifications in event-time order')
assert(fs.existsSync(runtimePath), 'the notification listener needs a bridge owner independent of the foreground service')
const runtime = fs.readFileSync(runtimePath, 'utf8')
assert(runtime.includes('RESTART_TASK') && runtime.includes('scheduleRestartLocked') && runtime.includes('postDelayed'), 'fatal bridge errors must recover through runtime-owned bounded backoff')
assert(runtime.indexOf('instance = runtime') < runtime.indexOf('server.start()'), 'runtime generation must be published before asynchronous WebSocket bind errors can arrive')
assert(runtime.includes('onServerStarted') && runtime.includes('current.started = true'), 'bridge readiness must be confirmed only by WebSocket onStart')
assert(listener.includes('NavBridgeRuntime.ensureStarted'), 'notification callbacks must bootstrap the local bridge without opening the phone UI')
assert(!service.includes('NavDataBus.setListener(this)'), 'foreground service must not be the sole in-process navigation bridge owner')
assert(service.includes('NavBridgeRuntime.ensureStarted'), 'foreground service must attach to the shared bridge runtime when available')
assert(activity.includes('isNotificationListenerAccessGranted'), 'activity must use the official notification access API')
assert(activity.includes('VERSION_CODES.O_MR1'), 'notification listener manager calls must be guarded at their API 27 introduction')
assert(service.includes('VERSION_CODES.O_MR1'), 'service notification listener manager calls must be guarded at their API 27 introduction')
assert(manifest.includes('POST_NOTIFICATIONS'), 'Android 13+ foreground-service status needs the notification permission declaration')
assert(activity.includes('requestNotificationsPermissionIfNeeded'), 'foreground-service notification permission must be requested from a foreground activity')
assert(androidBuild.includes('buildConfig true'), 'diagnostic version labels require AGP BuildConfig generation')
assert(!activity.includes('rebindAttempts < 6'), 'activity must not force re-authorization after a fixed retry count')
assert(service.indexOf('startForeground(NOTIFICATION_ID') < service.indexOf('ensureBridge();'), 'foreground service must enter foreground before attaching to the local bridge')
assert(service.includes('onTimeout(int startId, int fgsType)'), 'Android 15 dataSync timeout must stop the foreground service')
assert(service.includes('NavBridgeRuntime.isRunning'), 'dataSync timeout must not take down the notification-owned bridge')
assert(service.includes('stopSelf();'), 'dataSync timeout must unconditionally stop the expired foreground service')
assert(repository.includes('clearWatchAckLocked();'), 'ending a navigation session must clear its watch ACK timing')
assert(repository.includes('if (previousSeq != snapshot.optLong')
  && repository.includes('clearWatchAckLocked();'),
  'a new navigation sequence must not inherit a previous watch ACK timestamp')
assert(!service.includes('client(s): " + json'), 'navigation JSON with route text must never be written to Logcat')
const socketServer = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavWebSocketServer.java', 'utf8')
assert(socketServer.includes('LastNavCache.getFresh()'), 'reconnect must not replay expired navigation snapshots')
assert(socketServer.includes('NavBridgeRuntime.onFatalServerError'), 'fatal WebSocket failures must release the runtime for automatic restart')
assert(socketServer.includes('connection.isOpen()') && socketServer.includes('clients.remove(connection)'), 'closed localhost clients must be pruned from the bridge client set')
assert(socketServer.includes('setReuseAddr(true)'), 'bridge restarts must retain localhost address reuse for rapid port rebinding')
assert(socketServer.includes('setConnectionLostTimeout(0)'), 'server heartbeat must be disabled because ZeppOS can intentionally suspend App-Side while asleep')
assert(!socketServer.includes('"superseded"') && !socketServer.includes('existing.close'), 'parallel Zepp App-Side contexts must not evict each other and create a reconnect loop')
console.log('android lifecycle tests passed')
