const assert = require('assert')
const fs = require('fs')

const source = fs.readFileSync('page/navigation.js', 'utf8')

assert(source.includes('action: null, distance: null, instruction: null'), 'navigation page needs dedicated action and distance widgets')
assert(source.includes('actionTitle'), 'navigation page needs readable action labels')
assert(source.includes('this.clearArrow()'), 'waiting state must be text-only without any direction symbol')
assert(!source.includes('PROGRESS_Y'), 'navigation page must not show unverifiable route progress')
assert(source.includes('ACTION_TEXT_SIZE = 28'), 'maneuver title must be larger for glance reading')
assert(source.includes('ARROW_Y = 88') && source.includes('ARROW_SIZE = 152'), 'arrow needs a larger fixed visual slot')
assert(source.includes('DISTANCE_Y = 246'), 'distance needs a separate fixed slot')
assert(source.includes('INSTRUCTION_Y = 340') && source.includes('ROAD_Y = 378'), 'instruction and road slots must stay below distance')
assert(source.includes('INSTRUCTION_TEXT_SIZE = 24') && source.includes('BIG_INSTRUCTION_TEXT_SIZE = 26'), 'navigation instruction must use the larger fixed text sizes')
assert(source.includes('isBigTextEnabled() ? 14 : 15'), 'larger instruction text must use a safe circular-screen character limit')
assert(source.includes('drawThemeBackground(W)'), 'navigation page must render the selected theme through the shared background helper')
assert(fs.readFileSync('utils/theme.js', 'utf8').includes("src: 'night-corridor-bg.png'"), 'the original corridor artwork must remain a selectable theme')
assert(source.includes('appData.markApplied(nav)'), 'widget updates must emit applied ACK')
console.log('navigation hero layout tests passed')
