const assert = require('assert')
const fs = require('fs')

const app = fs.readFileSync('app.js', 'utf8')
const side = fs.readFileSync('app-side/index.js', 'utf8')
const home = fs.readFileSync('page/home.js', 'utf8')
const navigation = fs.readFileSync('page/navigation.js', 'utf8')
const android = fs.readFileSync('D:/ring/RingMap-android/app/src/main/java/com/ringmap/nav/NavNotificationListener.java', 'utf8')

assert(side.includes("sendToWatch('nav'"), 'app-side must forward every fresh Android navigation packet directly to the watch')
assert(side.includes("sendToWatch('nav_end'"), 'app-side must forward an explicit navigation-end packet')
assert(side.includes('lastNavData = null'), 'app-side must clear its recovery cache when navigation ends')
assert(app.includes('localStorage.removeItem(KEY_TS)'), 'watch app must clear the navigation timestamp when navigation ends')
assert(android.includes('onNotificationRemoved'), 'Android must detect removal of the navigation notification')
assert(android.includes('NavDataBus.clear'), 'Android must clear cached navigation when navigation ends')
assert(android.includes('导航结束'), 'Android must recognize explicit navigation-end notification text')

assert(app.includes('navPageActive'), 'app must track whether the navigation page is active')
assert(app.includes('navPageRefresh'), 'app must publish live navigation directly to the active page')
assert(app.includes('navRoutePending'), 'app must prevent duplicate navigation page pushes')
assert(app.includes('publishNavigation'), 'app must centralize live navigation publication')
assert(app.includes('requestLatestNav: requestLatestNav'), 'app must expose a cache-recovery request to the active navigation page')
assert(navigation.includes('renderNav(nav)'), 'navigation page needs a direct render method for live packets')
assert(navigation.includes('navPageRefresh = function'), 'navigation page must subscribe to app-level live navigation packets')
assert(navigation.includes('appData.requestLatestNav()'), 'navigation page must request the latest cached navigation when it opens')
assert(!navigation.includes('setInterval(function()'), 'navigation page must be event-driven while it is open')
assert(navigation.includes('getApp()._options.globalData'), 'navigation page must use ZeppOS app globalData access')
assert(!navigation.includes('按键返回'), 'navigation screen must not instruct users to use a hardware return key')
assert(!navigation.includes("from '@zos/router'"), 'navigation screen must not depend on router back behavior')
assert(!side.includes('setInterval(sendNavRequest, 5000)'), 'app-side must not use the backwards cache-request loop')
assert(home.includes('var hasNav = !!raw && status === \'navigating\''), 'home status must require actual nav data')
assert(home.includes('导航预览'), 'home must show a navigation preview during active navigation')
console.log('navigation lifecycle tests passed')
