const assert = require('assert')
const fs = require('fs')

const source = fs.readFileSync('page/navigation.js', 'utf8')

assert(source.includes('action: null, distance: null, instruction: null'), 'navigation page needs dedicated action and distance widgets')
assert(source.includes('actionTitle'), 'navigation page needs readable action labels')
assert(source.includes("this.renderArrow('wait')"), 'waiting state must not show a false straight arrow')
assert(!source.includes('PROGRESS_Y'), 'navigation page must not show unverifiable route progress')
assert(source.includes('ARROW_Y = 100') && source.includes('ARROW_SIZE = 128'), 'arrow needs a fixed visual slot')
assert(source.includes('DISTANCE_Y = 246'), 'distance needs a separate fixed slot')
assert(source.includes('INSTRUCTION_Y = 340') && source.includes('ROAD_Y = 378'), 'instruction and road slots must stay below distance')
assert(source.includes("src: 'night-corridor-bg.png'"), 'navigation page needs the original corridor artwork')
assert(source.includes('appData.markApplied(nav)'), 'widget updates must emit applied ACK')
console.log('navigation hero layout tests passed')
