const assert = require('assert')
const fs = require('fs')

const app = fs.readFileSync('app.js', 'utf8')
const side = fs.readFileSync('app-side/index.js', 'utf8')
const reducer = fs.readFileSync('shared/nav-state.js', 'utf8')
const home = fs.readFileSync('page/home.js', 'utf8')
const navigation = fs.readFileSync('page/navigation.js', 'utf8')
const android = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavNotificationListener.java', 'utf8')
const service = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavigationService.java', 'utf8')
const runtime = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavBridgeRuntime.java', 'utf8')
const server = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/NavWebSocketServer.java', 'utf8')

assert(side.includes("packet.type === 'nav_snapshot'"), 'app-side must forward protocol v2 snapshots')
assert(side.includes("packet.type === 'nav_end'"), 'app-side must handle structured navigation-end packets')
assert(side.includes('lastNavData = null'), 'app-side must clear its recovery cache when navigation ends')
assert(side.includes('connectionEpoch'), 'app-side must invalidate stale socket callbacks')
assert(side.includes("connectionState === 'connecting'"), 'app-side must guard a connection already in progress')
assert(side.includes("type: 'ping'"), 'app-side must maintain an application heartbeat')
assert(!side.includes('setInterval(sendNavRequest, 5000)'), 'app-side must not use the backwards cache-request loop')

assert(app.includes("from './shared/nav-state'"), 'watch app must use the protocol reducer')
assert(app.includes('reduceNavPacket'), 'watch app must reduce every packet through session and sequence rules')
assert(app.includes('expireNavState'), 'watch app must expire stale maneuver data')
assert(app.includes('localStorage.removeItem(KEY_TS)'), 'watch app must clear the navigation timestamp when navigation ends')
assert(app.includes('markApplied'), 'watch app must expose applied ACK reporting')
assert(reducer.includes("reason: 'different_session_end'") || reducer.includes("'different_session_end'"), 'old session end packets must be rejected')
assert(reducer.includes("'old_seq'"), 'old sequence packets must be rejected')

assert(android.includes('onNotificationRemoved'), 'Android must detect removal of the navigation notification')
assert(android.includes('LastNavCache.clear(end)'), 'Android listener must clear cache even if the foreground service is absent')
assert(android.includes('NavDataBus.clear(end)'), 'Android must publish a structured navigation-end packet')
assert(runtime.includes('server.broadcast(json)'), 'the notification-owned runtime must broadcast the structured end packet')
assert(!service.includes('broadcast("navend")') && !runtime.includes('broadcast("navend")'), 'the bridge must never emit a bare navend signal')
assert(server.includes('new JSONObject'), 'WebSocket server must parse device packets as JSON')
assert(!server.includes('contains("watch_ack")'), 'ACK detection must not use substring matching')

assert(app.includes('navPageActive'), 'app must track whether the navigation page is active')
assert(app.includes('navPageRefresh'), 'app must publish live navigation directly to the active page')
assert(app.includes('navRoutePending'), 'app must prevent duplicate navigation page pushes')
assert(app.includes('requestLatestNav: requestLatestNav'), 'app must expose snapshot recovery')
assert(app.includes('openNavigationPage: openNavigationPage'), 'app must expose guarded navigation routing for wake relaunch')
assert(navigation.includes('renderNav(nav, navState)'), 'navigation page needs a direct render method for live packets and global state')
assert(navigation.includes('navPageRefresh = function'), 'navigation page must subscribe to app-level live packets')
assert(navigation.includes('appData.requestLatestNav()'), 'navigation page must request the latest snapshot when it opens')
assert(!navigation.includes('setInterval(function()'), 'navigation page must remain event driven')
assert(navigation.includes('getApp()._options.globalData'), 'navigation page must use ZeppOS app globalData access')
assert(!navigation.includes('按键返回'), 'navigation screen must not instruct users to use a hardware return key')
assert(!navigation.includes("from '@zos/router'"), 'navigation screen must not depend on router back behavior')
assert(home.includes("appData.navState.status === 'active'"), 'home status must require an active protocol snapshot')
assert(app.includes('resumeNavigationOnHome'), 'app must track a one-shot wake recovery route')
assert(home.includes('if (appData.resumeNavigationOnHome)') && home.includes('appData.resumeNavigationOnHome = false'), 'home must consume wake navigation recovery only once')
assert(home.includes('appData.openNavigationPage()'), 'home must resume the navigation page after a screen-off relaunch with an active cached session')
assert(home.includes('actionTitle(type)'), 'home must show the current navigation action during an active session')
console.log('navigation lifecycle tests passed')
