const assert = require('assert')
const fs = require('fs')

const source = fs.readFileSync('page/navigation.js', 'utf8')
const icons = fs.readFileSync('utils/icons.js', 'utf8')

assert(source.includes("import { createActionIcon"), 'navigation page must use image action icons')
assert(source.includes('this.renderArrow(null)'), 'navigation page must clear the icon while waiting')
assert(source.includes('deleteAll(this.state.arrowWidgets)'), 'navigation page must delete the previous icon before redraw')
assert(source.includes('normalizedAction'), 'navigation page must normalize navigation actions')
assert(source.includes("indexOf('slight_left')") || source.includes("case 'slight_left'"), 'slight_left must have a dedicated mapping')
assert(source.includes("indexOf('slight_right')") || source.includes("case 'slight_right'"), 'slight_right must have a dedicated mapping')
assert(source.includes('this.state.lastAction'), 'icon redraw must be deduplicated by action')
assert(icons.includes('widget.IMG'), 'icon helper must create an image widget')
assert(icons.includes("straight: 'icon-up.png'"), 'straight icon must use the bundled PNG')
assert(icons.includes("left: 'icon-left.png'"), 'left icon must use the bundled PNG')
assert(icons.includes("right: 'icon-right.png'"), 'right icon must use the bundled PNG')
assert(icons.includes("uturn: 'icon-uturn.png'"), 'u-turn icon must use the bundled PNG')
assert(icons.includes("arrive: 'icon-arrive.png'"), 'arrive icon must use the bundled PNG')
assert(!source.includes('a.push(line'), 'legacy geometric arrow drawing must be removed')
console.log('navigation arrow behavior tests passed')
