const assert = require('assert')
const fs = require('fs')

const nav = fs.readFileSync('page/navigation.js', 'utf8')
const home = fs.readFileSync('page/home.js', 'utf8')
const theme = fs.readFileSync('utils/theme.js', 'utf8')
const androidApp = fs.readFileSync('android/app/src/main/java/com/ringmap/nav/RingMapApp.java', 'utf8')

assert(nav.includes('var CYAN = 0x2EDCF2'), 'watch navigation should use the corridor cyan signal color')
assert(nav.includes('drawThemeBackground(W)'), 'watch navigation should use the shared theme renderer')
assert(home.includes('drawThemeBackground(480)'), 'watch home should use the shared theme renderer')
assert(theme.includes("src: 'night-corridor-bg.png'") && theme.includes("src: 'anime-background.png'"), 'watch theme renderer must preserve corridor and anime bitmaps')
assert(nav.includes('0xF6FAF8') && nav.includes('0xB5C2C8'), 'watch must retain high contrast text hierarchy')
assert(!nav.includes('0x0F6B3A'), 'watch must not tint every icon green')
assert(androidApp.includes('DynamicColors.applyToActivitiesIfAvailable'), 'Android app must retain Monet dynamic colors')
assert(!androidApp.includes('setTheme') || androidApp.includes('DynamicColors'), 'Android theme must not become fixed color')
console.log('palette tests passed')
